import os

WHITE = 'white'
BLACK = 'black'

BOARD_IMAGE_FILE = os.path.join("resources", "images", "board.svg")
BOARD_SIZE = 600
SQUARE_SIZE = (BOARD_SIZE // 8)

PIECE_IMAGE_FILE = {
    'white': os.path.join("resources", "images", "white_piece.png"),
    'black': os.path.join("resources", "images", "black_piece.png")
}

VALID_SQUARES = [
    (SQUARE_SIZE*1, SQUARE_SIZE*0), ( SQUARE_SIZE*3, SQUARE_SIZE*0), (SQUARE_SIZE*5, SQUARE_SIZE*0), (SQUARE_SIZE*7, SQUARE_SIZE*0),
    (SQUARE_SIZE*0, SQUARE_SIZE*1), ( SQUARE_SIZE*2, SQUARE_SIZE*1), (SQUARE_SIZE*4, SQUARE_SIZE*1), (SQUARE_SIZE*6, SQUARE_SIZE*1),
    (SQUARE_SIZE*1, SQUARE_SIZE*2), ( SQUARE_SIZE*3, SQUARE_SIZE*2), (SQUARE_SIZE*5, SQUARE_SIZE*2), (SQUARE_SIZE*7, SQUARE_SIZE*2),
    (SQUARE_SIZE*0, SQUARE_SIZE*3), ( SQUARE_SIZE*2, SQUARE_SIZE*3), (SQUARE_SIZE*4, SQUARE_SIZE*3), (SQUARE_SIZE*6, SQUARE_SIZE*3),
    (SQUARE_SIZE*1, SQUARE_SIZE*4), ( SQUARE_SIZE*3, SQUARE_SIZE*4), (SQUARE_SIZE*5, SQUARE_SIZE*4), (SQUARE_SIZE*7, SQUARE_SIZE*4),
    (SQUARE_SIZE*0, SQUARE_SIZE*5), ( SQUARE_SIZE*2, SQUARE_SIZE*5), (SQUARE_SIZE*4, SQUARE_SIZE*5), (SQUARE_SIZE*6, SQUARE_SIZE*5),
    (SQUARE_SIZE*1, SQUARE_SIZE*6), ( SQUARE_SIZE*3, SQUARE_SIZE*6), (SQUARE_SIZE*5, SQUARE_SIZE*6), (SQUARE_SIZE*7, SQUARE_SIZE*6),
    (SQUARE_SIZE*0, SQUARE_SIZE*7), ( SQUARE_SIZE*2, SQUARE_SIZE*7), (SQUARE_SIZE*4, SQUARE_SIZE*7), (SQUARE_SIZE*6, SQUARE_SIZE*7),
]
